# Generated by Django 4.2 on 2023-04-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'can read all books')], 'verbose_name': 'book', 'verbose_name_plural': 'books'},
        ),
    ]
